version: "2"

formatters:
  enable:
    - gci
    - gofumpt

linters:
  default: all
  disable:
    - cyclop # duplicate of gocyclo
    - dupl
    - exhaustruct
    - forbidigo
    - gosec
    - lll
    - mnd
    - nlreturn
    - paralleltest
    - prealloc
    - rowserrcheck # not relevant (SQL)
    - sqlclosecheck # not relevant (SQL)
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/instana/testify
              desc: not allowed
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 16
    govet:
      enable:
        - shadow
    misspell:
      locale: US

  exclusions:
    presets:
      - comments
    rules:
      - path: version.go
        text: (version|date|commit) is a global variable
      - path: mjolnir.go
        text: (.+)RE is a global variable
      - path: mjolnir_test.go
        text: Function 'Test_parseIssueFixes' is too long

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
