run:
  timeout: 2m
linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 16
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/instana/testify"
            desc: not allowed
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
linters:
  enable-all: true
  disable:
    - execinquery # deprecated
    - gomnd # deprecated
    - cyclop # duplicate of gocyclo
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - lll
    - gosec
    - dupl
    - prealloc
    - wsl
    - nlreturn
    - testpackage
    - paralleltest
    - tparallel
    - wrapcheck
    - exhaustruct
    - forbidigo
    - mnd
    - ifshort
    - varnamelen

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'package-comments: should have a package comment'
  exclude-rules:
    - path: version.go
      text: (version|date|commit) is a global variable
    - path: mjolnir.go
      text: (.+)RE is a global variable
    - path: mjolnir_test.go
      text: Function 'Test_parseIssueFixes' is too long
