run:
  deadline: 2m
  skip-files: []
linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 16
  maligned:
    suggest-new: true
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - exhaustivestruct # deprecated
    - golint # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - nosnakecase # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - execinquery # not relevant (SQL)
    - cyclop # duplicate of gocyclo
    - lll
    - gas
    - dupl
    - prealloc
    - wsl
    - nlreturn
    - testpackage
    - paralleltest
    - tparallel
    - wrapcheck
    - exhaustruct
    - forbidigo
    - gomnd
    - ifshort
    - varnamelen

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'package-comments: should have a package comment'
  exclude-rules:
    - path: version.go
      text: (version|date|commit) is a global variable
    - path: mjolnir.go
      text: (.+)RE is a global variable
    - path: mjolnir_test.go
      text: Function 'Test_parseIssueFixes' is too long
